### ISSUE TITLE
"App" Has Stopped

### ISSUE THREAD

**Issue by bigbossmaher** [cowbell/cordova-plugin-geofence#220]
my app was working great .
when i add the plugin and run the app . i get "MyAppname " has stopped . 
this error is gone when i remove the plugin.
this is the logcat
04-19 01:51:02.995 2590-2713/? I/PackageManager: Removing non-system package:com.parking.tunisie
04-19 01:51:04.680 2590-2713/? I/PackageManager: Package com.parking.tunisie codePath changed from /data/app/com.parking.tunisie-2.apk to /data/app/com.parking.tunisie-1.apk; Retaining data and using new
04-19 01:51:08.650 10340-10340/? D/CapabilityManagerService: The package(com.parking.tunisie) updated
04-19 01:51:10.135 4162-4162/? E/SPPClientService: [PackageInfoChangeReceiver] [handlePkgRemovedEvent] PackageName : com.parking.tunisie, true, false
04-19 01:51:10.770 3482-12339/? D/Wear_Controller: Received broadcast action=android.intent.action.PACKAGE_REMOVED and uri=com.parking.tunisie
04-19 01:51:10.790 3482-6222/? E/Drive.UninstallOperation: Package still installed com.parking.tunisie
04-19 01:51:12.740 3482-12340/? D/Wear_Controller: Received broadcast action=android.intent.action.PACKAGE_ADDED and uri=com.parking.tunisie
04-19 01:51:13.280 12394-12394/com.parking.tunisie D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 0ms
04-19 01:51:13.345 12394-12394/com.parking.tunisie I/CordovaLog: Changing log level to DEBUG(3)
04-19 01:51:13.345 12394-12394/com.parking.tunisie I/CordovaActivity: Apache Cordova native platform version 6.1.2 is starting
04-19 01:51:13.345 12394-12394/com.parking.tunisie D/CordovaActivity: CordovaActivity.onCreate()
04-19 01:51:13.345 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method android.app.Activity.checkSelfPermission, referenced from method org.apache.cordova.CordovaInterfaceImpl.hasPermission
04-19 01:51:13.355 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve virtual method 28: Landroid/app/Activity;.checkSelfPermission (Ljava/lang/String;)I
04-19 01:51:13.355 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x6e at 0x0009
04-19 01:51:13.355 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method android.app.Activity.requestPermissions, referenced from method org.apache.cordova.CordovaInterfaceImpl.requestPermissions
04-19 01:51:13.355 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve virtual method 72: Landroid/app/Activity;.requestPermissions ([Ljava/lang/String;I)V
04-19 01:51:13.355 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x6e at 0x000a
04-19 01:51:13.360 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method android.webkit.WebView.setWebContentsDebuggingEnabled, referenced from method org.apache.cordova.engine.SystemWebViewEngine.enableRemoteDebugging
04-19 01:51:13.360 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve static method 11672: Landroid/webkit/WebView;.setWebContentsDebuggingEnabled (Z)V
04-19 01:51:13.360 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x71 at 0x0001
04-19 01:51:13.360 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method android.webkit.WebSettings.setMediaPlaybackRequiresUserGesture, referenced from method org.apache.cordova.engine.SystemWebViewEngine.initWebViewSettings
04-19 01:51:13.360 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve virtual method 11660: Landroid/webkit/WebSettings;.setMediaPlaybackRequiresUserGesture (Z)V
04-19 01:51:13.360 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x6e at 0x0080
04-19 01:51:13.370 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method org.apache.cordova.engine.SystemWebView.evaluateJavascript, referenced from method org.apache.cordova.engine.SystemWebViewEngine.evaluateJavascript
04-19 01:51:13.370 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve virtual method 22052: Lorg/apache/cordova/engine/SystemWebView;.evaluateJavascript (Ljava/lang/String;Landroid/webkit/ValueCallback;)V
04-19 01:51:13.370 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x6e at 0x0008
04-19 01:51:13.390 4294-4294/? I/Finsky: [1] com.google.android.finsky.utils.as.run(3288): Package state data is missing for com.parking.tunisie
04-19 01:51:13.515 12394-12394/com.parking.tunisie I/webclipboard: clipservice: android.sec.clipboard.ClipboardExManager@425835d0
04-19 01:51:13.530 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method android.webkit.CookieManager.setAcceptThirdPartyCookies, referenced from method org.apache.cordova.engine.SystemCookieManager.<init>
04-19 01:51:13.530 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve virtual method 11623: Landroid/webkit/CookieManager;.setAcceptThirdPartyCookies (Landroid/webkit/WebView;Z)V
04-19 01:51:13.530 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x6e at 0x001b
04-19 01:51:13.530 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method android.webkit.CookieManager.flush, referenced from method org.apache.cordova.engine.SystemCookieManager.flush
04-19 01:51:13.530 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve virtual method 11617: Landroid/webkit/CookieManager;.flush ()V
04-19 01:51:13.530 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x6e at 0x0008
04-19 01:51:13.540 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/webkit/ClientCertRequest;)
04-19 01:51:13.540 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/webkit/ClientCertRequest;)
04-19 01:51:13.540 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method android.webkit.WebViewClient.onReceivedClientCertRequest, referenced from method org.apache.cordova.engine.SystemWebViewClient.onReceivedClientCertRequest
04-19 01:51:13.540 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve virtual method 11677: Landroid/webkit/WebViewClient;.onReceivedClientCertRequest (Landroid/webkit/WebView;Landroid/webkit/ClientCertRequest;)V
04-19 01:51:13.540 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x6f at 0x001a
04-19 01:51:13.545 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/webkit/PermissionRequest;)
04-19 01:51:13.545 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method android.webkit.PermissionRequest.getResources, referenced from method org.apache.cordova.engine.SystemWebChromeClient.onPermissionRequest
04-19 01:51:13.545 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve virtual method 11635: Landroid/webkit/PermissionRequest;.getResources ()[Ljava/lang/String;
04-19 01:51:13.545 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x6e at 0x000d
04-19 01:51:13.545 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method android.webkit.WebChromeClient$FileChooserParams.createIntent, referenced from method org.apache.cordova.engine.SystemWebChromeClient.onShowFileChooser
04-19 01:51:13.545 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve virtual method 11640: Landroid/webkit/WebChromeClient$FileChooserParams;.createIntent ()Landroid/content/Intent;
04-19 01:51:13.545 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x6e at 0x0000
04-19 01:51:13.560 12394-12407/com.parking.tunisie V/webkit: BrowserFrame constructor: this=Handler (android.webkit.BrowserFrame) {4257d390}
04-19 01:51:13.560 12394-12394/com.parking.tunisie D/SystemWebViewEngine: CordovaWebView is running on device made by: samsung
04-19 01:51:13.575 12394-12394/com.parking.tunisie I/SystemWebViewEngine: Disabled addJavascriptInterface() bridge since Android version is old.
04-19 01:51:13.575 12394-12394/com.parking.tunisie D/PluginManager: init()
04-19 01:51:13.615 12394-12394/com.parking.tunisie D/dalvikvm: GC_FOR_ALLOC freed 205K, 12% free 8228K/9287K, paused 31ms, total 31ms
04-19 01:51:13.620 12394-12394/com.parking.tunisie I/dalvikvm-heap: Grow heap (frag case) to 9.421MB for 601616-byte allocation
04-19 01:51:13.645 12394-12407/com.parking.tunisie D/dalvikvm: GC_FOR_ALLOC freed 1K, 12% free 8814K/9927K, paused 26ms, total 26ms
04-19 01:51:13.695 12394-12397/com.parking.tunisie D/dalvikvm: GC_CONCURRENT freed 5K, 12% free 8828K/9927K, paused 12ms+2ms, total 51ms
04-19 01:51:13.705 4823-5000/? I/cm.log.servpro: [InstallMonitorReceiver][D]/ scanRemainFile: com.parking.tunisie true
04-19 01:51:13.705 12394-12394/com.parking.tunisie D/ProgressBar: setProgress = 0
04-19 01:51:13.710 12394-12394/com.parking.tunisie D/ProgressBar: setProgress = 0, fromUser = false
04-19 01:51:13.710 12394-12394/com.parking.tunisie D/ProgressBar: mProgress = 0mIndeterminate = false, mMin = 0, mMax = 100
04-19 01:51:13.715 12394-12394/com.parking.tunisie D/ProgressBar: setProgress = 0
04-19 01:51:13.720 12394-12394/com.parking.tunisie D/ProgressBar: setProgress = 0, fromUser = false
04-19 01:51:13.720 12394-12394/com.parking.tunisie D/ProgressBar: mProgress = 0mIndeterminate = false, mMin = 0, mMax = 10000
04-19 01:51:13.770 12394-12394/com.parking.tunisie I/CordovaLog: Changing log level to 5
04-19 01:51:13.775 12394-12394/com.parking.tunisie E/dalvikvm: Could not find class 'android.os.UserManager', referenced from method com.google.android.gms.common.zzg.zzaK
04-19 01:51:13.775 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve check-cast 245 (Landroid/os/UserManager;) in Lcom/google/android/gms/common/zzg;
04-19 01:51:13.775 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x1f at 0x000c
04-19 01:51:13.780 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.zzg.zzz
04-19 01:51:13.780 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve virtual method 477: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
04-19 01:51:13.780 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x6e at 0x0012
04-19 01:51:13.780 12394-12394/com.parking.tunisie E/dalvikvm: Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.internal.zzadf.zzg
04-19 01:51:13.780 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve check-cast 24 (Landroid/app/AppOpsManager;) in Lcom/google/android/gms/internal/zzadf;
04-19 01:51:13.780 12394-12394/com.parking.tunisie D/dalvikvm: VFY: replacing opcode 0x1f at 0x0010
04-19 01:51:13.790 12394-12394/com.parking.tunisie D/GoogleMapsPlugin: ----> checkGooglePlayServices = true
04-19 01:51:13.795 12394-12394/com.parking.tunisie W/dalvikvm: DexOpt: method is in an interface
04-19 01:51:13.795 12394-12394/com.parking.tunisie I/dalvikvm: Could not find method com.google.android.gms.dynamic.zze.zzA, referenced from method com.google.android.gms.maps.internal.zzai.zzbq
04-19 01:51:13.795 12394-12394/com.parking.tunisie W/dalvikvm: VFY: unable to resolve static method 13871: Lcom/google/android/gms/dynamic/zze;.zzA (Ljava/lang/Object;)Lcom/google/android/gms/dynamic/zzd;
04-19 01:51:13.795 12394-12394/com.parking.tunisie W/dalvikvm: VFY:  rejecting opcode 0x71 at 0x001d
04-19 01:51:13.795 12394-12394/com.parking.tunisie W/dalvikvm: VFY:  rejected Lcom/google/android/gms/maps/internal/zzai;.zzbq (Landroid/content/Context;)Lcom/google/android/gms/maps/internal/zzc;
04-19 01:51:13.795 12394-12394/com.parking.tunisie W/dalvikvm: Verifier rejected class Lcom/google/android/gms/maps/internal/zzai;
04-19 01:51:13.795 12394-12394/com.parking.tunisie D/AndroidRuntime: Shutting down VM
04-19 01:51:13.795 12394-12394/com.parking.tunisie W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41ca22a0)
04-19 01:51:13.795 12394-12394/com.parking.tunisie E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     java.lang.VerifyError: com/google/android/gms/maps/internal/zzai
                                                                         at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source)
                                                                         at plugin.google.maps.CordovaGoogleMaps$1.run(CordovaGoogleMaps.java:238)
                                                                         at android.app.Activity.runOnUiThread(Activity.java:4767)
                                                                         at plugin.google.maps.CordovaGoogleMaps.initialize(CordovaGoogleMaps.java:104)
                                                                         at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)
                                                                         at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
                                                                         at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
                                                                         at org.apache.cordova.PluginManager.init(PluginManager.java:86)
                                                                         at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:115)
                                                                         at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:149)
                                                                         at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
                                                                         at com.parking.tunisie.MainActivity.onCreate(MainActivity.java:39)
                                                                         at android.app.Activity.performCreate(Activity.java:5207)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2085)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2146)
                                                                         at android.app.ActivityThread.access$700(ActivityThread.java:140)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                         at android.os.Looper.loop(Looper.java:137)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:4947)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:511)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
                                                                         at dalvik.system.NativeStart.main(Native Method)

**Comment by bigbossmaher** [comment]
i think your geofence plugin can not work with https://github.com/mapsplugin/cordova-plugin-googlemaps
because when i delete one of them the app is work

**Comment by jonas-l-b** [comment]
Yes it does as explained here #191
