### ISSUE TITLE
App crashing with Android 7.0 Samsung devices after a while of using

### ISSUE THREAD

**Issue by AresDev** [cowbell/cordova-plugin-geofence#262]
I'm using the plugin for an app installed in a Samsung Galaxy S6 edge and a Samsung A5 2016  with Android 7.0, and after a while of using it, it crashes showing the following log in logcat:

FATAL EXCEPTION: main
                                                                  Process: io.ionic.starter, PID: 24225
                                                                  java.lang.RuntimeException: Unable to instantiate service com.cowbell.cordova.geofence.ReceiveTransitionsIntentService: java.lang.RuntimeException: Init failed
                                                                      at android.app.ActivityThread.handleCreateService(ActivityThread.java:3449)
                                                                      at android.app.ActivityThread.-wrap6(ActivityThread.java)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1721)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                   Caused by: java.lang.RuntimeException: Init failed
                                                                      at android.media.ToneGenerator.native_setup(Native Method)
                                                                      at android.media.ToneGenerator.<init>(ToneGenerator.java:855)
                                                                      at com.cowbell.cordova.geofence.BeepHelper.<init>(BeepHelper.java:10)
                                                                      at com.cowbell.cordova.geofence.ReceiveTransitionsIntentService.<init>(ReceiveTransitionsIntentService.java:26)
                                                                      at java.lang.Class.newInstance(Native Method)
                                                                      at android.app.ActivityThread.handleCreateService(ActivityThread.java:3446)
                                                                      at android.app.ActivityThread.-wrap6(ActivityThread.java) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1721) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:154) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6682) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 

I've also tested the app in a Moto-G 1st gen with Android 5.1 and a MotoG5 plus with Android 7 and it always works with no crashing. 

Please help

**Comment by adamalexander** [comment]
@AresDev Have you found a solution?
