### ISSUE TITLE
Can't build project after adding plugin

### ISSUE THREAD

**Issue by Floky87** [cowbell/cordova-plugin-geofence#61]
I have this error when building my project:

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)

This is my plugin list:

android.support.v4 21.0.1 "Android Support v4"
com.google.playservices 21.0.0 "Google Play Services for Android"
com.ionic.keyboard 1.0.4 "Keyboard"
com.phonegap.plugins.PushPlugin 2.4.0 "PushPlugin"
com.vladstirbu.cordova.promise 1.0.0 "Promise"
cordova-plugin-camera 1.1.0 "Camera"
cordova-plugin-crosswalk-webview 1.0.1-dev "Crosswalk WebView Engine"
cordova-plugin-file 2.0.0 "File"
cordova-plugin-file-transfer 1.1.0 "File Transfer"
cordova-plugin-geofence 0.4.0 "geofence"
cordova-plugin-geolocation 1.0.0 "Geolocation"
cordova-plugin-splashscreen 2.0.0 "Splashscreen"
cordova-plugin-whitelist 1.0.0 "Whitelist"
nl.x-services.plugins.socialsharing 4.3.19-dev "SocialSharing"
org.crosswalk.engine 0.0.1-dev "Crosswalk Engine"

I also use Ionic CLI for building.

**Comment by rudza** [comment]
http://stackoverflow.com/questions/30234573/cordova-build-failed-with-exception

Maybe this helps. :)

**Comment by tsubik** [comment]
@Chernov87 I don't think this is plugin issue. Have you checked this http://stackoverflow.com/questions/7870265/unable-to-execute-dex-multiple-dex-files-define-lcom-myapp-rarray

**Comment by PaperMonster** [comment]
Take a look at #18 . I think it is similar to this issue.

**Comment by tsubik** [comment]
Closed due inactivity.

**Comment by indikaanu83** [comment]
im facing the same issue here.Can anyone help me.im using command line to build the app
