### ISSUE TITLE
unable to remove plugin

### ISSUE THREAD

**Issue by DataHerder** [cowbell/cordova-plugin-geofence#93]
Hi, I am unable to remove the plugin, I'm getting this error:

```
TypeError: Cannot read property 'buffer' of undefined
    at walk_obj (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js:131:18)
    at walk_obj (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js:98:7)
    at walk_obj (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js:109:9)
    at Object.build (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js:76:3)
    at ConfigFile_save [as save] (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/ConfigFile.js:97:47)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/ConfigKeeper.js:61:49
    at Array.forEach (native)
    at ConfigKeeper_save_all [as save_all] (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/ConfigKeeper.js:59:31)
    at PlatformMunger_save_all [as save_all] (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/config-changes.js:82:24)
    at Object.exports.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/config-changes.js:59:12)
```

Please advise!

#UPDATE

node v4.2.1
cordova 5.3.3

**Comment by johnrobertcobbold** [comment]
Should be a bug somewhere with Cordova, it's affecting other plugins too. There is a bug report somewhere on the Apache website. Meanwhile, remove the IOS platform first and you will be able to remove the plugin, after which you can add back the platform again

**Comment by DataHerder** [comment]
This isn't good.  It definitely has something to do with cowbell because if I remove the platform and add it back I get: 

```
Failed to install 'com.cowbell.cordova.geofence':Error: Expected plugin to have ID "com.vladstirbu.cordova.promise" but got "es6-promise-plugin".
    at checkID (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:177:15)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:161:9
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
Error: Expected plugin to have ID "com.vladstirbu.cordova.promise" but got "es6-promise-plugin".
    at checkID (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:177:15)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:161:9
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
```

**Comment by tsubik** [comment]
Hey @DataHerder cordova team changed the way plugins should be installed few months ago. All plugins are moved to npm registry. Make sure you use the new way

```
cordova plugin add cordova-plugin-geofence
cordova plugin rm cordova-plugin-geofence
```

Also there was a cordova bug if you mixed new and old plugin names, but no idea if it is fixed or not.

I see I need to update readme also :smile:

**Comment by DataHerder** [comment]
Hey @tsubik - how ya doin?

So basically I have to wait to get this up and running til later this evening.  I'll have to reinstall the application in a new directory and reload the plugins manually this time.  They all seem to work just fine except yours and this could be due to the above reference.  I'll come back and post my result later today.

**Comment by DataHerder** [comment]
@tsubik - I have done that.  Looks like everything works fine... one HUGE problem though.  The application is an older version of Swift.  The application breaks when updating to the latest XCode project.  I have to download an earlier version of XCode to get this to compile correctly.  Are you guys working on updating it to the latest Swift?  This is probably very frustrating.  Newer versions break because of substantial changes to the syntax.  :-/

**Comment by tsubik** [comment]
Thanks for update.
