### ISSUE TITLE
Can't build project after adding plugin (Android)

### ISSUE THREAD

**Issue by indikaanu83** [cowbell/cordova-plugin-geofence#96]
have this error when building my project:

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/ads/AdReques
t$ErrorCode;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:50
2)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        F:\Android sdk latest\android-sdk-windows\build-tools\23.0.1\dx.bat --de
x --no-optimize --output E:\Local Projects\DressMate\Cordova\Cordova\ionWordpres
s_1.3.0\platforms\android\build\intermediates\dex\debug --input-list=E:\Local Pr
ojects\DressMate\Cordova\Cordova\ionWordpress_1.3.0\platforms\android\build\inte
rmediates\tmp\dex\debug\inputList.txt
Error Code:
        2
Output:

        UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dex.DexException: Multiple dex files define Lcom/google/ads/
AdRequest$ErrorCode;
                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.ja
va:596)
                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:
554)
                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:
535)
                at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)

                at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
                at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main
.java:502)
                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
                at com.android.dx.command.dexer.Main.run(Main.java:277)
                at com.android.dx.command.dexer.Main.main(Main.java:245)
                at com.android.dx.command.Main.main(Main.java:106)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 3.821 secs

E:\Local Projects\DressMate\Cordova\Cordova\ionWordpress_1.3.0\platforms\android
\cordova\node_modules\q\q.js:126
                    throw e;
                    ^
Error code 1 for command: cmd with args: /s /c ""E:\Local Projects\DressMate\Cor
dova\Cordova\ionWordpress_1.3.0\platforms\android\gradlew" cdvBuildDebug -b "E:\
Local Projects\DressMate\Cordova\Cordova\ionWordpress_1.3.0\platforms\android\bu
ild.gradle" -Dorg.gradle.daemon=true"
ERROR building one of the platforms: Error: cmd: Command failed with exit code 1

You may not have the required environment or OS to build this project
Error: cmd: Command failed with exit code 1
    at ChildProcess.whenDone (E:\Local Projects\DressMate\project\nodejs\node_mo
dules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js:139:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by tsubik** [comment]
This is not plugin related. More like a dependency hell problem described here http://stackoverflow.com/questions/22958979/multiple-dex-files-define-lcom-google-ads-adrequesterrorcode-and-multiple-dex-f
